class CapitalImageService {
  static final CapitalImageService _instance = CapitalImageService._internal();
  factory CapitalImageService() => _instance;
  CapitalImageService._internal();

  Set<String>? _availableCapitalPhotos;

  /// Get set of available capital photo filenames (without extension)
  Future<Set<String>> getAvailableCapitalPhotos() async {
    if (_availableCapitalPhotos != null) return _availableCapitalPhotos!;

    // Use manually defined set since we know exactly which photos we have
    _availableCapitalPhotos = _getKnownAvailablePhotos();
    return _availableCapitalPhotos!;
  }

  /// Check if a capital photo exists for given ISO2 code and capital slug
  Future<bool> hasCapitalPhoto(String iso2, String capitalSlug) async {
    final available = await getAvailableCapitalPhotos();
    final expectedFilename = '${iso2.toUpperCase()}_$capitalSlug';
    return available.contains(expectedFilename);
  }

  /// Get asset path for capital photo if it exists
  Future<String?> getCapitalPhotoPath(String iso2, String capitalSlug) async {
    final hasPhoto = await hasCapitalPhoto(iso2, capitalSlug);
    if (hasPhoto) {
      return 'assets/capital_photos/${iso2.toUpperCase()}_$capitalSlug.jpg';
    }
    return null;
  }

  /// Manually defined set of available photos (fallback)
  Set<String> _getKnownAvailablePhotos() {
    return {
      'AD_andorra-la-vella',
      'AE_abu-dhabi',
      'AF_kabul',
      'AL_tirana',
      'AM_yerevan',
      'AO_luanda',
      'AR_buenos-aires',
      'AT_vienna',
      'AU_canberra',
      'AZ_baku',
      'BA_sarajevo',
      'BB_bridgetown',
      'BD_dhaka',
      'BE_brussels',
      'BF_ouagadougou',
      'BG_sofia',
      'BH_manama',
      'BI_gitega',
      'BJ_porto-novo',
      'BN_bandar-seri-begawan',
      'BS_nassau',
      'BT_thimphu',
      'BW_gaborone',
      'BY_minsk',
      'BZ_belmopan',
      'CA_ottawa',
      'CD_kinshasa',
      'CF_bangui',
      'CH_bern',
      'CI_yamoussoukro',
      'CL_santiago',
      'CM_yaounde',
      'CN_beijing',
      'CO_bogota',
      'CG_brazzaville',
      'CK_avarua',
      'CR_san-jose',
      'CU_havana',
      'CV_praia',
      'CY_nicosia',
      'CZ_prague',
      'DE_berlin',
      'DJ_djibouti',
      'DK_copenhagen',
      'DM_roseau',
      'DO_santo-domingo',
      'DZ_algiers',
      'EC_quito',
      'EE_tallinn',
      'EG_cairo',
      'ER_asmara',
      'ES_madrid',
      'ET_addis-ababa',
      'FI_helsinki',
      'FJ_suva',
      'FR_paris',
      'GA_libreville',
      'GB_london',
      'GE_tbilisi',
      'GH_accra',
      'GM_banjul',
      'GN_conakry',
      'GQ_malabo',
      'GR_athens',
      'GD_st-georges',
      'GT_guatemala-city',
      'GY_georgetown',
      'HN_tegucigalpa',
      'HR_zagreb',
      'HT_port-au-prince',
      'HU_budapest',
      'ID_jakarta',
      'IE_dublin',
      'IL_jerusalem',
      'IN_new-delhi',
      'IQ_baghdad',
      'IR_tehran',
      'IS_reykjavik',
      'IT_rome',
      'JM_kingston',
      'JO_amman',
      'JP_tokyo',
      'KE_nairobi',
      'KG_bishkek',
      'KH_phnom-penh',
      'KI_south-tarawa',
      'KM_moroni',
      'KP_pyongyang',
      'KR_seoul',
      'KW_kuwait-city',
      'KZ_astana',
      'LA_vientiane',
      'LB_beirut',
      'LC_castries',
      'LI_vaduz',
      'LK_sri-jayawardenepura-kotte',
      'LR_monrovia',
      'LS_maseru',
      'LT_vilnius',
      'LU_luxembourg',
      'LV_riga',
      'LY_tripoli',
      'MA_rabat',
      'MC_monaco',
      'MG_antananarivo',
      'MH_majuro',
      'MK_skopje',
      'ML_bamako',
      'MM_naypyidaw',
      'MN_ulan-bator',
      'MR_nouakchott',
      'MT_valletta',
      'MU_port-louis',
      'MW_lilongwe',
      'MX_mexico-city',
      'MY_kuala-lumpur',
      'MZ_maputo',
      'NA_windhoek',
      'NE_niamey',
      'NG_abuja',
      'NI_managua',
      'NL_amsterdam',
      'NO_oslo',
      'NP_kathmandu',
      'NR_yaren',
      'NZ_wellington',
      'OM_muscat',
      'PA_panama-city',
      'PE_lima',
      'PG_port-moresby',
      'PH_manila',
      'PK_islamabad',
      'PL_warsaw',
      'PT_lisbon',
      'PW_ngerulmud',
      'QA_doha',
      'RO_bucharest',
      'RS_belgrade',
      'RU_moscow',
      'RW_kigali',
      'SA_riyadh',
      'SB_honiara',
      'SC_victoria',
      'SD_khartoum',
      'SE_stockholm',
      'SG_singapore',
      'SI_ljubljana',
      'SK_bratislava',
      'SL_freetown',
      'SM_city-of-san-marino',
      'SN_dakar',
      'SO_mogadishu',
      'SR_paramaribo',
      'SS_juba',
      'SV_san-salvador',
      'SZ_mbabane',
      'SY_damascus',
      'TD_ndjamena',
      'TG_lome',
      'TH_bangkok',
      'TJ_dushanbe',
      'TL_dili',
      'TM_ashgabat',
      'TN_tunis',
      'TO_nukualofa',
      'TR_ankara',
      'TT_port-of-spain',
      'TV_funafuti',
      'TZ_dodoma',
      'UA_kyiv',
      'UG_kampala',
      'UY_montevideo',
      'UZ_tashkent',
      'VA_vatican-city',
      'VC_kingstown',
      'VE_caracas',
      'VN_hanoi',
      'VU_port-vila',
      'WS_apia',
      'YE_sanaa',
      'ZA_pretoria',
      'ZM_lusaka',
      'ZW_harare'
    };
  }

  void clearCache() {
    _availableCapitalPhotos = null;
  }
}
